#Application url
url_old=https://opensource-demo.orangehrmlive.com/web/index.php/auth/login	
url=http://localhost/orangehrm/web/index.php/auth/login

#Browser
browser=chrome

#Credentials 
username_old=admin
username=orangehrm_dinesh
password_old=admin123
password=103R1a0464.

#wait (seconds)
implicitWait=10

#Explicit wait
explicitwait = 30
